### ISSUE TITLE
Ошибка при обработке int.vim

### ISSUE THREAD

**Issue by BaltsevichDanil** [alexey-goloburdin/nvim-config#11]
При запуске nvim выползает такая ошибка:
``строка  372:
E5108: Error executing lua [string ":lua"]:1: module 'autosave' not found:
        no field package.preload['autosave']
        no file './autosave.lua'
        no file '/opt/homebrew/share/luajit-2.1.0-beta3/autosave.lua'
        no file '/usr/local/share/lua/5.1/autosave.lua'
        no file '/usr/local/share/lua/5.1/autosave/init.lua'
        no file '/opt/homebrew/share/lua/5.1/autosave.lua'
        no file '/opt/homebrew/share/lua/5.1/autosave/init.lua'
        no file './autosave.so'
        no file '/usr/local/lib/lua/5.1/autosave.so'
        no file '/opt/homebrew/lib/lua/5.1/autosave.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
`` 

Попробовал удалить модуль autosave, тогда запускается без ошибок, но тема почему-то не применяется, все черно-белое.

**Comment by Mozheykin** [comment]
> При запуске nvim выползает такая ошибка: `строка 372: E5108: Error executing lua [string ":lua"]:1: module 'autosave' not found: no field package.preload['autosave'] no file './autosave.lua' no file '/opt/homebrew/share/luajit-2.1.0-beta3/autosave.lua' no file '/usr/local/share/lua/5.1/autosave.lua' no file '/usr/local/share/lua/5.1/autosave/init.lua' no file '/opt/homebrew/share/lua/5.1/autosave.lua' no file '/opt/homebrew/share/lua/5.1/autosave/init.lua' no file './autosave.so' no file '/usr/local/lib/lua/5.1/autosave.so' no file '/opt/homebrew/lib/lua/5.1/autosave.so' no file '/usr/local/lib/lua/5.1/loadall.so' stack traceback: [C]: in function 'require' [string ":lua"]:1: in main chunk `
> 
> Попробовал удалить модуль autosave, тогда запускается без ошибок, но тема почему-то не применяется, все черно-белое.

☝ плагин Autosave переехал и теперь значится как auto-save.nvim

**Comment by Nikisa151** [comment]
Всем здрасте, решил установить neovim по видео и при его запуске выводит ошибки:
E5108: Error executing lua ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't instal
led: ...a/.vim/plugged/telescope-fzf-native.nvim/lua/fzf_lib.lua:11: /home/n1k1sa/.vim/plugged/telescope-fzf-native.nvim/lua/../build/li
bfzf.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
stack traceback:
        [C]: in function 'error'
        ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
        ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:62: in function 'load_extension'
        [string ":lua"]:1: in main chunk

**Comment by cer2891** [comment]
Плагины установил, в куча ошибок все равно:
Обнаружена ошибка при обработке /home/cer/.config/nvim/init.vim:                                       
строка  257:
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:2: attempt to index field 'o' (a nil value)
строка  371:
E5105: Error while calling lua chunk: ...e/cer/.vim/plugged/auto-save.nvim/lua/auto-save/init.lua:17: attempt to call field 'nvim_create_augroup' (a nil value)                                                
строка  376:
E5105: Error while calling lua chunk: ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: /home/cer/.vim/plugged/plenary.nvim/lua/plenary/path.lua:19: attempt to index field 'loop' (a nil value)

**Comment by cer2891** [comment]
Похоже вот этот блок не работает: 

lua << EOF
EOF
