### ISSUE TITLE
inoremap jk <esc>

### ISSUE THREAD

**Issue by Korolev-Oleg** [alexey-goloburdin/nvim-config#2]
Инструкция ```inoremap jk <esc>``` похожа на костыль
что бы её не использовать можно для yank подключить системный буфер обмена ```set clipboard=unnamedplus```
и вернуть стандартный ctrl + c для выхода из вставки ```map <C-c> <esc>```

**Comment by alexey-goloburdin** [comment]
Идея `jk` для выхода из insert режима в том, чтобы выходить из него быстрее, не тянуться до ESС или других комбинаций. Клавиши jk в центре, удобно. Хотя, признаться, я этим пока не пользуюсь, чаще просто ESC по привычке.
