### ISSUE TITLE
Какие то ошибки в конфете

### ISSUE THREAD

**Issue by Kishinskiy** [alexey-goloburdin/nvim-config#3]
Обнаружена ошибка при обработке /Users/kishinskii/.config/nvim/init.vim:
строка   18:
E117: Неизвестная функция: plug#begin
строка   20:
E492: Это не команда редактора: Plug 'neovim/nvim-lspconfig'
строка   21:
E492: Это не команда редактора: Plug 'hrsh7th/nvim-cmp'
строка   22:
E492: Это не команда редактора: Plug 'hrsh7th/cmp-nvim-lsp'
строка   23:
E492: Это не команда редактора: Plug 'saadparwaiz1/cmp_luasnip'
строка   24:
E492: Это не команда редактора: Plug 'L3MON4D3/LuaSnip'
строка   28:
E492: Это не команда редактора: Plug 'morhetz/gruvbox'  " colorscheme gruvbox
строка   29:
E492: Это не команда редактора: Plug 'mhartington/oceanic-next'  " colorscheme O
ceanicNext
строка   30:
E492: Это не команда редактора: Plug 'kaicataldo/material.vim', { 'branch': 'mai
n' }
строка   31:
E492: Это не команда редактора: Plug 'ayu-theme/ayu-vim'
строка   34:

**Comment by Korolev-Oleg** [comment]
did you install vim-plug?
https://github.com/junegunn/vim-plug#neovim

**Comment by alexey-goloburdin** [comment]
@Kishinskiy скорее всего не установлен vim-plug, да
